source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "11.0"
use_frameworks!

abstract_target 'SamplePods' do
    pod 'SpotifyLogin', :path => '../..'
    
    target 'Sample' do
    end

    target 'SampleTests' do
    end 
end
